matrix:
	g++ -Wall --std=c++11 Matrix.cpp transitMatrix.cpp threadUtilities.cpp dataFrame.cpp userDataContainer.cpp Graph.cpp MinHeap.cpp protobuf/p2p.pb.cc -o matrix -lprotobuf -lpthread
debug:
	g++ --std=c++11 Matrix.cpp transitMatrix.cpp threadUtilities.cpp dataFrame.cpp userDataContainer.cpp Graph.cpp MinHeap.cpp protobuf/p2p.pb.cc -o matrix -g -lprotobuf -lpthread
clean:
	rm matrix